### ISSUE TITLE
Align HTTP span data keys

### ISSUE THREAD

**Issue by brustolin** [getsentry/sentry-cocoa#2393]
### Description

Currently, cocoa SDK has 4 extra informations for HTTP spans that are not specified in the documentation:

```objc
    [netSpan setTagValue:[NSString stringWithFormat:@"%@", statusCode] forKey:@"http.status_code"];
    [netSpan setDataValue:sessionTask.currentRequest.HTTPMethod forKey:@"method"];
    [netSpan setDataValue:sessionTask.currentRequest.URL.path forKey:@"url"];
    [netSpan setDataValue:@"fetch" forKey:@"type"];
```

With the exception of the `type` that is not found anywhere else, every other information is duplicated.
- status code is used as the span finish status
- method and url are being used as the span description

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3076
- [x] rename `method` to `http.method`
- [x] document attribute `url` for Mobile on [Span Data Convetions doc](https://develop.sentry.dev/sdk/performance/span-data-conventions/)
- [x] document `fetch` for attribute `type` for Mobile on [Span Data Convetions doc](https://develop.sentry.dev/sdk/performance/span-data-conventions/)
```

**Comment by brustolin** [comment]
@marandaneto You once ask me to update the specs to include this informations. After reading the documentation, I really believe we should remove this from the SDK.

What do you think?

**Comment by philipphofmann** [comment]
Related develop docs PR https://github.com/getsentry/develop/pull/760

**Comment by marandaneto** [comment]
> @marandaneto You once ask me to update the specs to include this informations. After reading the documentation, I really believe we should remove this from the SDK.
> 
> What do you think?

Which information?
SDKs set the `method` and `url` as part of the `description`, not as part of the `data`, so I'm unsure why Cocoa does this.
Similar issue https://github.com/getsentry/develop/issues/445 also not added by any other Mobile SDK.

**Comment by marandaneto** [comment]
After a quick research, I suspect this comes from [here](https://github.com/getsentry/sentry/blob/fef9c695a1a7d3384fb3ce7ec6c264632e77061d/src/sentry/interfaces/spans.py#L33).
No other Mobile SDK does that, so either @brustolin somebody else told you to add it or you've seen somewhere else, but that's not the point anyway.
I'm unsure if this info should be removed or added, we'd need to understand how this info is used in the BE/FE, for example, the `http.status_code` as [stated before](https://github.com/getsentry/develop/issues/445) is used in the UI, so removing it would degrade that field.

**Comment by brustolin** [comment]
> we'd need to understand how this info is used in the BE/FE

Im pretty sure the extra data/tag mentioned in the issue description is not used by BE/FE, somehow this ended up in the SDK, but since this is not documented anywhere, imo, we should not keep it.

**Comment by marandaneto** [comment]
I'd not be so sure, as I said, I found those `data` fields in the [FE code](https://github.com/getsentry/sentry/blob/fef9c695a1a7d3384fb3ce7ec6c264632e77061d/static/app/components/events/interfaces/spans/spanTreeModel.spec.tsx#L47), I just don't know where this is displayed, but if it's mapped in there and they match it here, I am pretty sure that there's a hidden feature somewhere.

**Comment by kahest** [comment]
related: https://github.com/getsentry/sentry-cocoa/issues/2943

**Comment by kahest** [comment]
related: https://github.com/getsentry/sentry-cocoa/issues/3076 (for `http.status_code`)

**Comment by kahest** [comment]
`method` should be changed to `http.method` according to dev docs (see also [newer FE code](https://github.com/getsentry/sentry/blob/41420f400bb20689d8c9dc92dac823053779da0c/static/app/components/events/interfaces/spans/spanTreeModel.spec.tsx#L68) for reference).
