### ISSUE TITLE
MetricKit MXDiagnosticPayload GA

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#2585]
### Description

Experimental initial issue: https://github.com/getsentry/sentry-cocoa/issues/1661

Items to complete for making the MetricKit integration GA:

```[tasklist]
### Tasks
- [x] https://github.com/getsentry/sentry-cocoa/issues/2591 required for the next task
- [x] Fix calculate image size issue
- [x] #2738
- [ ] https://github.com/getsentry/sentry-cocoa/issues/2846
- [ ] https://github.com/getsentry/sentry-cocoa/issues/2847
- [x] Validate grouping and stacktraces with customer data
- [ ] https://github.com/getsentry/sentry-docs/pull/8186
- [x] Process MetricKit payloads on a background thread.
```

**Comment by philipphofmann** [comment]
We completed all items to make the MetricKit integration GA.

One blocker was that the integration also reports issues of the Cocoa SDK. I documented my reasoning for not doing that here https://github.com/getsentry/sentry-cocoa/issues/2847#issuecomment-1759209982:

> After some investigation in https://github.com/getsentry/sentry-cocoa/pull/3176, we can conclude that doing this reliably on the client side is complicated. We could discard such events on the backend, but then we kind of lie. If MetricKit detects an issue inside our SDK we shouldn't discard the issue, but report it. We can collect such issues alongside with our SDK crashes and try to fix them: https://github.com/getsentry/sentry/issues/57961.
