### ISSUE TITLE
Add experimental support for VisionOS

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3362]
### Description

Add experimental support for VisionOS. We need to add a sample application and test which features work for VisionOS. Furthermore, we should check that you can install the SDK for VisionOS with CocoaPods, Carthage, and SPM.

| Feature                         | VisionOS | 
|---------------------------------|-----|
| Crashes with symbolication      |   ✅   |
| Error events with symbolication |   ✅  |
| OOMs                            |   We can't test this on a simulator  |
| App hangs                       |   ✅   |
| Release health                  |   ✅   |
| View hierarchy                  |   ✅  |
| Screenshots                     |   ✅  |
| Auto-generated breadcrumbs      |  ✅   |
| Attachments                     |   ✅  |
| App start                       |   ✅   |
| Slow & frozen frames            |   Frame rate detected correctly, but on simulator mostly slow frames. We need a real device to test this properly.  |
| TTID/TTFD                       |  Not working with SwiftUI yet   |
| Network tracking                |  ✅   |
| File I/O tracking               |   ✅   |
| Core data tracking              |  Should work out of the box. Didn't want to spend time adding db to the sample.   |
| User interaction tracking       |  ✅   |
| Swift UI tracking               |   ✅   |
| MetricKit                       |   We can't test this on a simulator   |
| Profiling                       |   ✅   |   

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3101
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3323
- [ ] https://github.com/getsentry/sentry-docs/pull/8416
```

**Comment by armcknight** [comment]
I added another task (https://github.com/getsentry/sentry-cocoa/issues/3410) to implement/verify that we're adding xrOS slices in our xcframeworks built by carthage. We already use the required version of carthage, but might not yet be using the required version of Xcode in CI to do so. Not sure if it's work reopening this epic issue or not.

**Comment by philipphofmann** [comment]
@armcknight, I don't think it's required to reopen this issue. The goal was to have experimental support, which we achieved. Experimental means it may have bugs 😄.
