### ISSUE TITLE
[EPIC] App Start Tracing Improvements

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3465]
### Description

A collection of tasks for improving the app start tracing experience.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3345
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3530
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3471
```

**Comment by philipphofmann** [comment]
We completed all nonbreaking tasks. More improvements that are breaking are in https://github.com/getsentry/sentry-cocoa/issues/3562.
