### ISSUE TITLE
Add frames delay for transactions and spans

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3481]
### Description

See https://github.com/getsentry/team-mobile/issues/160.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3482
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3483
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3487
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3496
```
