### ISSUE TITLE
[EPIC] App Start Tracing Improvements V9

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3562]
### Description

A meta issue for collecting tasks for app start improvements in the next major v9.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3461
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3464
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3535
- [ ] 
```

**Comment by philprime** [comment]
Closing this, asm eta issues are managed as Linear projects now.
