### ISSUE TITLE
[cocoa] Add support for Sentry Metrics

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-cocoa#3631]
### Description
Metrics! Sentry will support Metrics finally! First we need all of our SDKs to support Metrics, including iOS

#### Requirements:

- [x] Metrics API
- [x] Tag normalization
- [x] Metrics Summary

#### Document(s)
[Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/)
[SDK Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/sending-metrics-sdk/)
[Product Specs](https://develop.sentry.dev/sdk/metrics/)

```[tasklist]
### Tasks
- [x] https://github.com/getsentry/sentry-cocoa/pull/3676
- [x] https://github.com/getsentry/sentry-cocoa/pull/3744
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3762
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3782
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3773
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3791
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3792
```
