### ISSUE TITLE
Metrics API Beta Follow Up

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#3790]
### Description

With https://github.com/getsentry/sentry-cocoa/issues/3631, the Cocoa SDK gets initial support for the Metrics API. This meta issue collects open tasks to complete after the initial beta launch.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3795
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3799
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3829
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3805
- [ ] https://github.com/getsentry/sentry-docs/issues/9614
- [ ] https://github.com/getsentry/sentry-cocoa/pull/3812
```
