### ISSUE TITLE
TTID/TTFD for SwiftUI

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-cocoa#4162]
### Problem Statement

What it says on the tin. :)

Please upvote if this is important to you.

### Solution Brainstorm

Might/will require introducing new APIs to call manually

### Tasks

- [X] Implementation: [https://github.com/getsentry/sentry-cocoa/pull/4596](https://github.com/getsentry/sentry-cocoa/pull/4596)
- [X] Support for `sentryTrace`: [https://github.com/getsentry/sentry-cocoa/issues/4787](https://github.com/getsentry/sentry-cocoa/issues/4787)
- [X] ~~Mark as experimental in code~~ [https://github.com/getsentry/sentry-cocoa/pull/4869](https://github.com/getsentry/sentry-cocoa/pull/4869)
- [X] Docs (see [https://github.com/getsentry/sentry-cocoa/issues/4162#issuecomment-2663444176](https://github.com/getsentry/sentry-cocoa/issues/4162#issuecomment-2663444176))
- [X] ~~TBD: Add feature usage tracking?~~

**Comment by kahest** [comment]
relevant docs pages:
- https://docs.sentry.io/platforms/apple/guides/ios/features/experimental-features/
- https://docs.sentry.io/platforms/apple/guides/ios/tracing/instrumentation/automatic-instrumentation/#time-to-initial-display
- https://docs.sentry.io/platforms/apple/guides/ios/tracing/instrumentation/automatic-instrumentation/#time-to-full-display
- https://docs.sentry.io/platforms/apple/guides/ios/tracing/instrumentation/swiftui-instrumentation/

**Comment by philprime** [comment]
The docs should clarify the following question:

> If we use the update view modifier with waitForFullDisplay set to true, do we still need to call SentrySDK.reportFullyDisplayed() and from where?

**Comment by philprime** [comment]
Superseded by https://github.com/getsentry/sentry-docs/pull/15638
