### ISSUE TITLE
[Apple] App Hangs improvements

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#4261]
### Description

The implementation of AppHangs has a few drawbacks, see https://github.com/getsentry/sentry-cocoa/discussions/2715. The main problem is that non-fully blocking app hangs have random stacktraces, which aren't actionable. Ideally, we plan on linking such app hangs to profiles, but we haven't decided how to achieve this in the product. Until we decide, we can give the users an option to ignore non-fully blocking app hangs. Furthermore, we plan on adding support for the app hang rate, but for that we need to capture fatal app hangs first, which we currently don't do.

Still, we can do some improvements for AppHangs

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cocoa/pull/4724
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3492
- [ ] https://github.com/getsentry/sentry-cocoa/issues/2216
- [ ] https://github.com/getsentry/sentry-cocoa/issues/4260
```

**Comment by philipphofmann** [comment]
With SR GA, and the upcoming mobile workshop I'm going to host, I see a low chance that I will deliver this by the end of this quarter. I'm sorry, we have to move this, @kahest.

**Comment by philipphofmann** [comment]
@kahest, again, I'm sorry, but the deserializing of events is going a bit slower than expected. I would like to have enough time for Phil for proper onboarding. I would like to push this by another two weeks.

**Comment by philipphofmann** [comment]
I watched my sick family quite a bit in the last week. So this will be delayed for roughly another week.

**Comment by philipphofmann** [comment]
Extracted app hangs rate into its own milestone: https://github.com/getsentry/sentry-cocoa/issues/3319, as discussed with @kahest. All improvements are finished.
