### ISSUE TITLE
Envelopes Serialization Improvements

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry-cocoa#4338]
### Description

After crashing the SDK on startup due to corrupted envelope data with https://github.com/getsentry/sentry-cocoa/issues/4280, we must ensure this doesn't happen again. This is a meta issue to collect the improvements to achieve that goal. The plan is to increase the test coverage mainly for SentryFileManager and SentrySerialization to cover more edge cases and reduce the probability of introducing bugs by future changes to these critical classes. Furthermore, we want to double-check if some edge cases could lead to unwanted behavior.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cocoa/pull/4312
- [ ] https://github.com/getsentry/sentry-cocoa/pull/4337
- [ ] https://github.com/getsentry/sentry-cocoa/pull/4341
- [ ] https://github.com/getsentry/sentry-cocoa/pull/4342
- [ ] https://github.com/getsentry/sentry-cocoa/pull/4343
- [ ] https://github.com/getsentry/sentry-cocoa/pull/4344
- [ ] https://github.com/getsentry/sentry-cocoa/pull/4345
- [ ] https://github.com/getsentry/sentry-cocoa/pull/4349
- [ ] https://github.com/getsentry/sentry-cocoa/pull/4348
```

**Comment by philipphofmann** [comment]
The root cause of https://github.com/getsentry/sentry-cocoa/issues/4280 was crashing while deserializing a corrupted envelope. We added plenty of new tests to cover more edge cases. This should do it for now.
